# Generated by Django 4.0.3 on 2022-06-26 14:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
